### ISSUE TITLE
Allow external Sass Files

### ISSUE THREAD

**Issue by timschoch** [jedfoster/SassMeister#163]
We're develolping a Framework and for documentation purposes it would be realy helpful to provide sassmeister examples where our employees can see what a specific mixin or function does and play around with how it.

The Problem, there is alot of sass code involved that needs to be present for the example to work. This has to be prior to the code of the example, so I would have to add all the framework code first and the user would have to scroll past it to get to the example -> unggh

Something like this would be neat:
```scss
/// @import 'http://path.to/framework.scss'
div {
  width: someFunction( 2 );
}
```

If possible, only the output of the sassmeister file would be shown in the CSS tab. CSS Output from the Framework should not be shown to make it easier for the user to see the changes
