### ISSUE TITLE
Editing on /gist/ URLs doesn’t work

### ISSUE THREAD

**Issue by brookjordan** [jedfoster/SassMeister#209]
When editing code from a gist link ([in this case, this one](https://www.sassmeister.com/gist/924de14a0702f09d995396b0273f8270)) the compiling loader never ends and the console shows a 404 and unhandled rejection errors.

If I copy and paste the same code into a [the normal SassMeister](https://www.sassmeister.com/) input then it works fine.

I noticed it hits different URLS on the gist version and the clean version:
- Gist URL: https://www.sassmeister.com/app/compile
- Clean version URL: https://www.sassmeister.com/app/dart/compile

On the gist link, when trying to change the `3` to an `8`, the console shows:
```css
Failed to load resource: the server responded with a status of 404 (Not Found)

app-eb3bc8c09e.min.js:3 Possibly unhandled rejection:
{
  "data": "<h1>Not Found</h1>",
  "status": 404,
  "config": {
    "method": "POST",
    "transformRequest": [null],
    "transformResponse": [null],
    "jsonpCallbackParam": "callback",
    "data": {
      "input": "
        @mixin multi-line-ellipsis($line-count) {
          /* autoprefixer: off */
          /* stylelint-disable-next-line value-no-vendor-prefix */
          display: -webkit-box;
          /* stylelint-disable property-no-vendor-prefix */
          -webkit-line-clamp: $line-count;
          -webkit-box-orient: vertical;
          /* stylelint-enable property-no-vendor-prefix */
          /* autoprefixer: on */
        }
        
        .card {
            @include multi-line-ellipsis(8);
        }
      ",
      "syntax": "scss",
      "original_syntax": "scss",
      "output_style": "expanded"
    },
    "url": "/app/compile",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8"
    }
  },
  "statusText": "Not Found",
  "xhrStatus": "complete",
  "resource": {
    "input": "
        @mixin multi-line-ellipsis($line-count) {
        /* autoprefixer: off */
        /* stylelint-disable-next-line value-no-vendor-prefix */
        display: -webkit-box;
        /* stylelint-disable property-no-vendor-prefix */
        -webkit-line-clamp: $line-count;
        -webkit-box-orient: vertical;
        /* stylelint-enable property-no-vendor-prefix */
        /* autoprefixer: on */
      }
      
      .card {
          @include multi-line-ellipsis(8);
      }
    ",
    "syntax": "scss",
    "original_syntax": "scss",
    "output_style": "expanded"
  }
}
```
